export const SKILL_NAME_TO_ID: Record<string, string> = {
  "admin": "admin",
  "advocate": "advocate",
  "animals": "animals",
  "art": "art",
  "astrogation": "astrogation",
  "athletics": "athletics",
  "broker": "broker",
  "carouse": "carouse",
  "deception": "deception",
  "diplomat": "diplomat",
  "drive": "drive",
  "electronics": "electronics",
  "engineer": "engineer",
  "explosives": "explosives",
  "flyer": "flyer",
  "gambler": "gambler",
  "gunner": "gunner",
  "gun combat": "guncombat",
  "guncombat": "guncombat",
  "heavy weapons": "heavyweapons",
  "heavyweapons": "heavyweapons",
  "independence": "independence",
  "investigate": "investigate",
  "jack of all trades": "jackofalltrades",
  "jack-of-all-trades": "jackofalltrades",
  "jackofalltrades": "jackofalltrades",
  "language": "language",
  "leadership": "leadership",
  "mechanic": "mechanic",
  "medic": "medic",
  "melee": "melee",
  "navigation": "navigation",
  "persuade": "persuade",
  "pilot": "pilot",
  "profession": "profession",
  "recon": "recon",
  "science": "science",
  "seafarer": "seafarer",
  "stealth": "stealth",
  "steward": "steward",
  "streetwise": "streetwise",
  "survival": "survival",
  "tactics": "tactics",
  "vacc suit": "vaccsuit",
  "vaccsuit": "vaccsuit",
  "telepathy": "telepathy",
  "clairvoyance": "clairvoyance",
  "telekinesis": "telekinesis",
  "awareness": "awareness",
  "teleportation": "teleportation"
};

export const SPECIALITY_NAME_TO_ID: Record<string, string> = {
  "strength": "strength",
  "dexterity": "dexterity",
  "endurance": "endurance",
  "handling": "handling",
  "vetinary": "vetinary",
  "veterinary": "vetinary",
  "training": "training",
  "performer": "performer",
  "holography": "holography",
  "instrument": "instrument",
  "visual media": "visualMedia",
  "write": "write",
  "hovercraft": "hovercraft",
  "mole": "mole",
  "track": "track",
  "walker": "walker",
  "wheel": "wheel",
  "comms": "comms",
  "computers": "computers",
  "remote ops": "remoteOps",
  "remoteops": "remoteOps",
  "sensors": "sensors",
  "m-drive": "mDrive",
  "mdrive": "mDrive",
  "j-drive": "jDrive",
  "jdrive": "jDrive",
  "life support": "lifeSupport",
  "lifesupport": "lifeSupport",
  "power": "power",
  "airship": "airship",
  "grav": "grav",
  "ornithopter": "ornithopter",
  "rotor": "rotor",
  "wing": "wing",
  "turret": "turret",
  "ortillery": "ortillery",
  "screen": "screen",
  "capital": "capital",
  "archaic": "archaic",
  "energy": "energy",
  "slug": "slug",
  "artillery": "artillery",
  "portable": "portable",
  "man portable": "portable",
  "vehicle": "vehicle",
  "galanglic": "galanglic",
  "anglic": "galanglic",
  "vilani": "vilani",
  "zdetl": "zdetl",
  "oynprith": "oynprith",
  "trokh": "trokh",
  "gvegh": "gvegh",
  "bilanidin": "vilani",
  "unarmed": "unarmed",
  "blade": "blade",
  "bludgeon": "bludgeon",
  "natural": "natural",
  "small craft": "smallCraft",
  "smallcraft": "smallCraft",
  "spacecraft": "spacecraft",
  "capital ships": "capitalShips",
  "capitalships": "capitalShips",
  "belter": "belter",
  "biologicals": "biologicals",
  "civil engineering": "civilEngineering",
  "civilengineering": "civilEngineering",
  "construction": "construction",
  "hydroponics": "hydroponics",
  "polymers": "polymers",
  "robotics": "robotics",
  "farming": "biologicals",
  "archaeology": "archaeology",
  "astronomy": "astronomy",
  "biology": "biology",
  "chemistry": "chemistry",
  "cosmology": "cosmology",
  "cybernetics": "cybernetics",
  "economics": "economics",
  "genetics": "genetics",
  "history": "history",
  "linguistics": "linquistics",
  "linquistics": "linquistics",
  "philosophy": "philosophy",
  "physics": "physics",
  "planetology": "planetology",
  "psionicology": "psionicology",
  "psychology": "psychology",
  "sophontology": "sophontology",
  "xenology": "xenology",
  "ocean ships": "oceanShips",
  "oceanships": "oceanShips",
  "personal": "personal",
  "sail": "sail",
  "submarine": "submarine",
  "military": "military",
  "naval": "naval"
};

export function skillId(name: string): string | undefined {
  return SKILL_NAME_TO_ID[normalize(name)];
}

export function specialityId(name?: string | null): string | undefined {
  if (!name) return undefined;
  return SPECIALITY_NAME_TO_ID[normalize(name)] ?? normalize(name).replace(/[^a-z0-9]/g, "");
}

function normalize(value: string): string {
  return value.trim().toLowerCase();
}
